module.exports = [
    'beforeIteration',
    'beforeItem',
    'beforePrerequest',
    'prerequest',
    'beforeRequest',
    'request',
    'beforeTest',
    'assertion',
    'test',
    'item',
    'iteration',
    'beforeScript',
    'script',
];
